"""Auto-exclude generated, vendored, build, and test fixture code."""
from __future__ import annotations

import re
from pathlib import Path

# Directory patterns to exclude
EXCLUDED_DIRS: set[str] = {
    # Vendored / third-party
    "vendor",
    "node_modules",
    "third_party",
    "third-party",
    "external",
    # Build artifacts
    "dist",
    "build",
    "out",
    ".next",
    "target",
    "_build",
    # Test fixtures / snapshots
    "__snapshots__",
    "testdata",
    "fixtures",
    "test_fixtures",
    # VCS
    ".git",
    ".svn",
    ".hg",
    # Python artifacts
    "__pycache__",
    ".pytest_cache",
    ".mypy_cache",
    ".ruff_cache",
    "*.egg-info",
    # Virtual environments
    "venv",
    ".venv",
    "env",
    ".env",
    # IDE / editor
    ".idea",
    ".vscode",
    # Misc
    ".tox",
    ".nox",
    "coverage",
    "htmlcov",
}

# File patterns for generated code
GENERATED_FILE_PATTERNS: list[re.Pattern[str]] = [
    re.compile(r".*_pb2\.py$"),
    re.compile(r".*_pb2_grpc\.py$"),
    re.compile(r".*\.gen\.go$"),
    re.compile(r".*\.generated\.\w+$"),
    re.compile(r".*\.snap$"),
    re.compile(r".*\.fixture\.\w+$"),
    re.compile(r".*\.min\.js$"),
    re.compile(r".*\.bundle\.js$"),
]

# File header markers for generated code
GENERATED_MARKERS: list[str] = [
    "DO NOT EDIT",
    "AUTO-GENERATED",
    "Code generated by",
    "This file is auto-generated",
    "Generated by",
    "@generated",
    "AUTOGENERATED FILE",
    "automatically generated",
]

# Migration file patterns
MIGRATION_PATTERNS: list[re.Pattern[str]] = [
    re.compile(r"\d{4}_.*\.py$"),  # Django migrations
    re.compile(r"\d+_create_.*\.rb$"),  # Rails migrations
    re.compile(r"V\d+__.*\.sql$"),  # Flyway migrations
]


def is_excluded_dir(dir_path: Path) -> bool:
    """Check if a directory should be excluded."""
    return dir_path.name in EXCLUDED_DIRS


def is_generated_file(file_path: Path) -> bool:
    """Check if file matches generated code patterns."""
    name = file_path.name
    for pattern in GENERATED_FILE_PATTERNS:
        if pattern.match(name):
            return True
    return False


def has_generated_header(file_path: Path, max_lines: int = 10) -> bool:
    """Check if file has a generated code marker in its header."""
    try:
        with open(file_path, "r", errors="ignore") as f:
            for i, line in enumerate(f):
                if i >= max_lines:
                    break
                upper = line.upper()
                for marker in GENERATED_MARKERS:
                    if marker.upper() in upper:
                        return True
    except (OSError, UnicodeDecodeError):
        pass
    return False


def is_migration_file(file_path: Path) -> bool:
    """Check if file is an ORM migration."""
    name = file_path.name
    for pattern in MIGRATION_PATTERNS:
        if pattern.match(name):
            return True
    return False


def should_exclude(
    file_path: Path,
    project_root: Path,
    include_overrides: list[str] | None = None,
) -> bool:
    """Determine if a file should be excluded from analysis.

    include_overrides takes precedence -- if a path matches an override,
    it is NOT excluded regardless of other rules.
    """
    try:
        rel = str(file_path.relative_to(project_root))
    except ValueError:
        return True

    if include_overrides:
        for override in include_overrides:
            if rel.startswith(override) or override.startswith(rel):
                return False

    # Check parent directories
    rel_parts = file_path.relative_to(project_root).parts
    for part in rel_parts[:-1]:  # skip the filename itself
        if part in EXCLUDED_DIRS:
            return True

    if is_generated_file(file_path):
        return True
    if has_generated_header(file_path):
        return True
    if is_migration_file(file_path):
        return True

    return False


def collect_files(
    project_root: Path,
    config_include: list[str] | None = None,
    config_exclude: list[str] | None = None,
    auto_exclude: bool = True,
    auto_exclude_override: list[str] | None = None,
    languages: list[str] | None = None,
) -> tuple[list[Path], list[Path]]:
    """Collect source files for analysis.

    Returns (included_files, excluded_files) so users can verify exclusions.
    """
    from argus.recon.parser import EXTENSION_MAP

    included: list[Path] = []
    excluded: list[Path] = []

    # Determine which extensions to look for
    if languages:
        valid_extensions = {
            ext for ext, lang in EXTENSION_MAP.items() if lang in languages
        }
    else:
        valid_extensions = set(EXTENSION_MAP.keys())

    # Determine scan roots
    if config_include:
        scan_roots = [project_root / p for p in config_include]
    else:
        scan_roots = [project_root]

    config_exclude_set = set(config_exclude or [])

    for scan_root in scan_roots:
        if not scan_root.exists():
            continue

        for file_path in scan_root.rglob("*"):
            if not file_path.is_file():
                continue
            if file_path.suffix.lower() not in valid_extensions:
                continue

            # Check explicit excludes
            try:
                rel = str(file_path.relative_to(project_root))
            except ValueError:
                continue

            if any(rel.startswith(ex) for ex in config_exclude_set):
                excluded.append(file_path)
                continue

            # Check auto-exclusions
            if auto_exclude and should_exclude(
                file_path, project_root, auto_exclude_override
            ):
                excluded.append(file_path)
                continue

            included.append(file_path)

    return included, excluded
