"""Tests for auto-exclusion logic."""
from pathlib import Path

import pytest

from argus.recon.exclusions import (
    EXCLUDED_DIRS,
    GENERATED_FILE_PATTERNS,
    GENERATED_MARKERS,
    collect_files,
    has_generated_header,
    is_excluded_dir,
    is_generated_file,
    is_migration_file,
    should_exclude,
)


class TestExcludedDirs:
    def test_vendor(self):
        assert is_excluded_dir(Path("vendor"))

    def test_node_modules(self):
        assert is_excluded_dir(Path("node_modules"))

    def test_build(self):
        assert is_excluded_dir(Path("build"))

    def test_dist(self):
        assert is_excluded_dir(Path("dist"))

    def test_pycache(self):
        assert is_excluded_dir(Path("__pycache__"))

    def test_venv(self):
        assert is_excluded_dir(Path("venv"))

    def test_dot_git(self):
        assert is_excluded_dir(Path(".git"))

    def test_fixtures(self):
        assert is_excluded_dir(Path("fixtures"))

    def test_regular_dir_not_excluded(self):
        assert not is_excluded_dir(Path("src"))

    def test_regular_lib_not_excluded(self):
        assert not is_excluded_dir(Path("lib"))


class TestGeneratedFilePatterns:
    def test_pb2_py(self):
        assert is_generated_file(Path("user_pb2.py"))

    def test_pb2_grpc_py(self):
        assert is_generated_file(Path("service_pb2_grpc.py"))

    def test_gen_go(self):
        assert is_generated_file(Path("types.gen.go"))

    def test_generated_extension(self):
        assert is_generated_file(Path("schema.generated.ts"))

    def test_min_js(self):
        assert is_generated_file(Path("app.min.js"))

    def test_bundle_js(self):
        assert is_generated_file(Path("vendor.bundle.js"))

    def test_snap(self):
        assert is_generated_file(Path("component.snap"))

    def test_regular_file_not_generated(self):
        assert not is_generated_file(Path("app.py"))

    def test_regular_js_not_generated(self):
        assert not is_generated_file(Path("server.js"))


class TestGeneratedHeaderDetection:
    def test_do_not_edit_header(self, tmp_path):
        f = tmp_path / "gen.py"
        f.write_text("# DO NOT EDIT - auto-generated\ndef foo(): pass\n")
        assert has_generated_header(f)

    def test_auto_generated_header(self, tmp_path):
        f = tmp_path / "gen.go"
        f.write_text("// AUTO-GENERATED by protoc\npackage main\n")
        assert has_generated_header(f)

    def test_code_generated_by(self, tmp_path):
        f = tmp_path / "gen.java"
        f.write_text("// Code generated by swagger-codegen\npublic class Foo {}\n")
        assert has_generated_header(f)

    def test_generated_annotation(self, tmp_path):
        f = tmp_path / "gen.py"
        f.write_text("# @generated\nimport os\n")
        assert has_generated_header(f)

    def test_normal_header_not_detected(self, tmp_path):
        f = tmp_path / "app.py"
        f.write_text('"""Application module."""\nimport os\n')
        assert not has_generated_header(f)

    def test_marker_after_max_lines_not_detected(self, tmp_path):
        f = tmp_path / "late.py"
        lines = ["# line\n"] * 15 + ["# DO NOT EDIT\n"]
        f.write_text("".join(lines))
        assert not has_generated_header(f)


class TestMigrationFiles:
    def test_django_migration(self):
        assert is_migration_file(Path("0001_initial.py"))

    def test_rails_migration(self):
        assert is_migration_file(Path("20210101_create_users.rb"))

    def test_flyway_migration(self):
        assert is_migration_file(Path("V1__create_table.sql"))

    def test_regular_file_not_migration(self):
        assert not is_migration_file(Path("app.py"))


class TestIncludeOverrides:
    def test_override_bypasses_exclusion(self, tmp_path):
        project_root = tmp_path / "project"
        vendor_dir = project_root / "vendor" / "lib"
        vendor_dir.mkdir(parents=True)
        f = vendor_dir / "util.py"
        f.write_text("def util(): pass\n")
        assert not should_exclude(f, project_root, include_overrides=["vendor/lib"])

    def test_without_override_excluded(self, tmp_path):
        project_root = tmp_path / "project"
        vendor_dir = project_root / "vendor"
        vendor_dir.mkdir(parents=True)
        f = vendor_dir / "util.py"
        f.write_text("def util(): pass\n")
        assert should_exclude(f, project_root)


class TestCollectFiles:
    def test_collect_files_python_app(self, python_app):
        # python_app is inside tests/fixtures which is excluded by default.
        # We use auto_exclude=False to avoid that.
        included, excluded = collect_files(
            python_app,
            auto_exclude=False,
            languages=["python"],
        )
        filenames = {f.name for f in included}
        assert "app.py" in filenames
        assert "models.py" in filenames

    def test_collect_files_respects_language_filter(self, python_app):
        included, _ = collect_files(
            python_app,
            auto_exclude=False,
            languages=["javascript"],
        )
        # No JS files in python_app
        assert len(included) == 0

    def test_collect_files_excludes_node_modules(self, tmp_path):
        # Create a structure with node_modules
        src = tmp_path / "src"
        src.mkdir()
        (src / "app.js").write_text("console.log('hello');")
        nm = tmp_path / "node_modules" / "pkg"
        nm.mkdir(parents=True)
        (nm / "index.js").write_text("module.exports = {};")

        included, excluded = collect_files(tmp_path, auto_exclude=True)
        included_names = {f.name for f in included}
        assert "app.js" in included_names
        assert "index.js" not in included_names
